export const STATES = [
  ['AL', 'Alabama'], ['AK', 'Alaska'], ['AZ', 'Arizona'], ['AR', 'Arkansas'],
  ['CA', 'California'], ['CO', 'Colorado'], ['CT', 'Connecticut'], ['DE', 'Delaware'],
  ['DC', 'D.C.'], ['FL', 'Florida'], ['GA', 'Georgia'], ['HI', 'Hawaii'],
  ['ID', 'Idaho'], ['IL', 'Illinois'], ['IN', 'Indiana'], ['IA', 'Iowa'],
  ['KS', 'Kansas'], ['KY', 'Kentucky'], ['LA', 'Louisiana'], ['ME', 'Maine'],
  ['MD', 'Maryland'], ['MA', 'Massachusetts'], ['MI', 'Michigan'], ['MN', 'Minnesota'],
  ['MS', 'Mississippi'], ['MO', 'Missouri'], ['MT', 'Montana'], ['NE', 'Nebraska'],
  ['NV', 'Nevada'], ['NH', 'New Hampshire'], ['NJ', 'New Jersey'], ['NM', 'New Mexico'],
  ['NY', 'New York'], ['NC', 'North Carolina'], ['ND', 'North Dakota'], ['OH', 'Ohio'],
  ['OK', 'Oklahoma'], ['OR', 'Oregon'], ['PA', 'Pennsylvania'], ['RI', 'Rhode Island'],
  ['SC', 'South Carolina'], ['SD', 'South Dakota'], ['TN', 'Tennessee'], ['TX', 'Texas'],
  ['UT', 'Utah'], ['VT', 'Vermont'], ['VA', 'Virginia'], ['WA', 'Washington'],
  ['WV', 'West Virginia'], ['WI', 'Wisconsin'], ['WY', 'Wyoming'],
]

// Per-state plate "skins" — each captures the real plate's color scheme, name
// color, number color, slogan, and a faint background icon. bg can be any CSS
// background value (solid or gradient). Keeps every tile visually distinct.
export const PLATE_THEMES = {
  AL: { bg: '#fbfbf7', name: '#c8102e', num: '#1a1a1a', slogan: 'Sweet Home Alabama', icon: '⭐' },
  AK: { bg: 'linear-gradient(180deg,#ffffff,#eaf0ee)', name: '#0b3d68', num: '#0b3d68', slogan: 'The Last Frontier', icon: '❄️' },
  AZ: { bg: 'linear-gradient(180deg,#6a3d8f,#b0552f 65%,#e0a04a)', name: '#ffffff', num: '#ffffff', slogan: 'Grand Canyon State', icon: '🌵' },
  AR: { bg: '#fbfbf7', name: '#b31942', num: '#1a1a1a', slogan: 'The Natural State', icon: '💎' },
  CA: { bg: '#ffffff', name: '#b5121b', num: '#12224f', slogan: 'The Golden State', icon: '🐻' },
  CO: { bg: 'linear-gradient(160deg,#1c6b3c,#0c4d29)', name: '#ffffff', num: '#ffffff', slogan: 'Colorful Colorado', icon: '⛰️' },
  CT: { bg: 'linear-gradient(180deg,#ffffff,#dfeaf5)', name: '#12386b', num: '#12386b', slogan: 'Constitution State', icon: '🌳' },
  DE: { bg: '#0b2a5b', name: '#f2c14e', num: '#f2c14e', slogan: 'The First State', icon: '⚓' },
  DC: { bg: '#ffffff', name: '#c8102e', num: '#1a1a1a', slogan: 'Taxation Without Representation', icon: '🏛️' },
  FL: { bg: '#ffffff', name: '#2e8b3d', num: '#e07b1a', slogan: 'Sunshine State', icon: '🍊' },
  GA: { bg: 'linear-gradient(180deg,#ffffff,#ffe7e0)', name: '#d98b6a', num: '#1a1a1a', slogan: 'Peach State', icon: '🍑' },
  HI: { bg: '#ffffff', name: '#1f6fb0', num: '#1f6fb0', slogan: 'Aloha State', icon: '🌈' },
  ID: { bg: 'linear-gradient(180deg,#cfe0ef,#eef4f0)', name: '#b31942', num: '#1a3d6b', slogan: 'Famous Potatoes', icon: '🥔' },
  IL: { bg: 'linear-gradient(180deg,#ffffff,#bcd2e8)', name: '#1a2a6b', num: '#b31942', slogan: 'Land of Lincoln', icon: '🎩' },
  IN: { bg: '#ffffff', name: '#12386b', num: '#12386b', slogan: 'Crossroads of America', icon: '🏁' },
  IA: { bg: 'linear-gradient(180deg,#2a5b8c,#9ec6e0)', name: '#ffffff', num: '#ffffff', slogan: 'The Hawkeye State', icon: '🌽' },
  KS: { bg: 'linear-gradient(180deg,#e9d9a8,#f5efd8)', name: '#8a6d1f', num: '#1a1a1a', slogan: 'The Sunflower State', icon: '🌻' },
  KY: { bg: 'linear-gradient(180deg,#7fb2e0,#eaf3fb)', name: '#1a3d6b', num: '#1a3d6b', slogan: 'Unbridled Spirit', icon: '🐎' },
  LA: { bg: '#ffffff', name: '#1e5aa0', num: '#1e5aa0', slogan: "Sportsman's Paradise", icon: '🦩' },
  ME: { bg: '#ffffff', name: '#b31942', num: '#1a1a1a', slogan: 'Vacationland', icon: '🦞' },
  MD: { bg: '#ffffff', name: '#b31942', num: '#1a1a1a', slogan: 'The Old Line State', icon: '🦀' },
  MA: { bg: '#ffffff', name: '#c8102e', num: '#c8102e', slogan: 'The Spirit of America', icon: '🎣' },
  MI: { bg: 'linear-gradient(180deg,#ffffff,#dfeef0)', name: '#1e5aa0', num: '#1e5aa0', slogan: 'Pure Michigan', icon: '💧' },
  MN: { bg: 'linear-gradient(180deg,#cfe0ef,#eef4f0)', name: '#1a3d6b', num: '#1a3d6b', slogan: '10,000 Lakes', icon: '💧' },
  MS: { bg: '#ffffff', name: '#2e6b3a', num: '#1a1a1a', slogan: "Birthplace of America's Music", icon: '🎸' },
  MO: { bg: 'linear-gradient(180deg,#ffffff,#cfe0ef)', name: '#1a3d6b', num: '#b31942', slogan: 'The Show-Me State', icon: '🐦' },
  MT: { bg: 'linear-gradient(180deg,#2a5b8c,#9ec6e0)', name: '#ffffff', num: '#ffffff', slogan: 'Big Sky Country', icon: '⛰️' },
  NE: { bg: 'linear-gradient(180deg,#ffffff,#e9e0c8)', name: '#1a3d6b', num: '#1a1a1a', slogan: 'The Good Life', icon: '🌽' },
  NV: { bg: 'linear-gradient(180deg,#3a6ea0,#e8eef4)', name: '#ffffff', num: '#12386b', slogan: 'The Silver State', icon: '🎰' },
  NH: { bg: '#ffffff', name: '#2e6b3a', num: '#2e6b3a', slogan: 'Live Free or Die', icon: '🏔️' },
  NJ: { bg: '#f3ecc4', name: '#3a3a3a', num: '#3a3a3a', slogan: 'Garden State', icon: '🌻' },
  NM: { bg: 'linear-gradient(180deg,#2aa7a7,#1f8f8f)', name: '#ffd24a', num: '#ffd24a', slogan: 'Land of Enchantment', icon: '☀️' },
  NY: { bg: 'linear-gradient(180deg,#ffffff,#f0d98a)', name: '#1a3d6b', num: '#1a3d6b', slogan: 'Excelsior', icon: '🗽' },
  NC: { bg: 'linear-gradient(180deg,#cfe0ef,#eef4f0)', name: '#b31942', num: '#1a3d6b', slogan: 'First in Flight', icon: '✈️' },
  ND: { bg: 'linear-gradient(180deg,#e0a04a,#efc98a)', name: '#5a3a1f', num: '#5a3a1f', slogan: 'Peace Garden State', icon: '🦬' },
  OH: { bg: 'linear-gradient(180deg,#ffffff,#cfe4ef)', name: '#c8102e', num: '#1a3d6b', slogan: 'The Heart of It All', icon: '✈️' },
  OK: { bg: 'linear-gradient(180deg,#cfe0ef,#eef4f0)', name: '#1a3d6b', num: '#1a3d6b', slogan: 'Native America', icon: '🪶' },
  OR: { bg: 'linear-gradient(180deg,#eaf4ea,#cfe6d2)', name: '#2e6b3a', num: '#2e6b3a', slogan: 'Pacific Wonderland', icon: '🌲' },
  PA: { bg: 'linear-gradient(180deg,#ffffff,#cfe0ef)', name: '#1a3d6b', num: '#1a3d6b', slogan: 'The Keystone State', icon: '🔔' },
  RI: { bg: '#ffffff', name: '#1a3d6b', num: '#1a3d6b', slogan: 'Ocean State', icon: '⛵' },
  SC: { bg: '#ffffff', name: '#1a3d6b', num: '#1a3d6b', slogan: 'The Palmetto State', icon: '🌴' },
  SD: { bg: 'linear-gradient(180deg,#2a7d4a,#eef0d8)', name: '#ffffff', num: '#2a5b2f', slogan: 'Mount Rushmore State', icon: '🗻' },
  TN: { bg: 'linear-gradient(180deg,#ffffff,#dfeee2)', name: '#2e6b3a', num: '#1a1a1a', slogan: 'The Volunteer State', icon: '🎵' },
  TX: { bg: '#ffffff', name: '#1a1a1a', num: '#1a1a1a', slogan: 'The Lone Star State', icon: '⭐' },
  UT: { bg: 'linear-gradient(180deg,#d98a3a,#efc27a)', name: '#7a3a1f', num: '#7a3a1f', slogan: 'Life Elevated', icon: '🏜️' },
  VT: { bg: '#1f6b3a', name: '#ffffff', num: '#ffffff', slogan: 'Green Mountain State', icon: '🍁' },
  VA: { bg: 'linear-gradient(180deg,#ffffff,#cfe0ef)', name: '#1a3d6b', num: '#1a3d6b', slogan: 'Virginia is for Lovers', icon: '❤️' },
  WA: { bg: 'linear-gradient(180deg,#cfe0ef,#ffffff)', name: '#1a3d6b', num: '#1a3d6b', slogan: 'The Evergreen State', icon: '🏔️' },
  WV: { bg: 'linear-gradient(180deg,#ffffff,#e9dcc0)', name: '#1a3d6b', num: '#8a6d1f', slogan: 'Wild, Wonderful', icon: '⛰️' },
  WI: { bg: 'linear-gradient(180deg,#ffffff,#f0e4c0)', name: '#b31942', num: '#1a1a1a', slogan: "America's Dairyland", icon: '🧀' },
  WY: { bg: '#ffffff', name: '#b31942', num: '#8a1a2a', slogan: 'Forever West', icon: '🐎' },
}

export const TRIVIA = [
  { q: 'Which U.S. interstate is the longest?', a: ['I-90', 'I-80', 'I-10', 'I-95'], c: 0 },
  { q: 'What is the tallest mountain in Colorado?', a: ['Pikes Peak', 'Mount Elbert', 'Longs Peak', 'Mount Evans'], c: 1 },
  { q: 'Route 66 famously ran from Chicago to which city?', a: ['San Francisco', 'Los Angeles', 'Santa Monica', 'San Diego'], c: 2 },
  { q: 'Which state has the most national parks?', a: ['Alaska', 'Utah', 'California', 'Colorado'], c: 2 },
  { q: 'What animal is on the Wyoming license plate?', a: ['Buffalo', 'Bucking horse and rider', 'Eagle', 'Elk'], c: 1 },
  { q: 'The Gateway Arch is in which city?', a: ['Kansas City', 'St. Louis', 'Memphis', 'Nashville'], c: 1 },
  { q: 'Which is the only U.S. state that borders just one other state?', a: ['Maine', 'Florida', 'Alaska', 'Rhode Island'], c: 0 },
  { q: 'What does a yellow diamond road sign usually mean?', a: ['Stop ahead', 'Warning', 'Construction', 'No passing'], c: 1 },
  { q: 'Mount Rushmore is in which state?', a: ['North Dakota', 'Wyoming', 'South Dakota', 'Montana'], c: 2 },
  { q: 'Which Great Lake is entirely within the U.S.?', a: ['Erie', 'Huron', 'Superior', 'Michigan'], c: 3 },
  { q: 'What is the capital of Texas?', a: ['Houston', 'Dallas', 'Austin', 'San Antonio'], c: 2 },
  { q: 'Old Faithful is found in which national park?', a: ['Yosemite', 'Yellowstone', 'Zion', 'Glacier'], c: 1 },
  { q: 'Even-numbered interstates generally run which direction?', a: ['North–south', 'East–west', 'Diagonal', 'In loops'], c: 1 },
  { q: 'Which state is nicknamed the "Centennial State"?', a: ['Utah', 'Nevada', 'Colorado', 'Kansas'], c: 2 },
  { q: 'The Grand Canyon is carved by which river?', a: ['Rio Grande', 'Colorado River', 'Snake River', 'Green River'], c: 1 },
  { q: 'What is the largest state by area?', a: ['Texas', 'California', 'Alaska', 'Montana'], c: 2 },
  { q: 'Which fast-food chain started as a root beer stand in 1919?', a: ['A&W', 'Sonic', 'Dairy Queen', "Wendy's"], c: 0 },
  { q: 'How many U.S. states start with the letter "M"?', a: ['6', '7', '8', '9'], c: 2 },
  { q: 'The world\'s first national park is:', a: ['Yosemite', 'Grand Canyon', 'Yellowstone', 'Great Smoky Mountains'], c: 2 },
  { q: 'Which state\'s license plates say "Live Free or Die"?', a: ['Vermont', 'New Hampshire', 'Maine', 'Montana'], c: 1 },
  { q: 'What is the only U.S. state capital without a McDonald\'s?', a: ['Juneau, AK', 'Montpelier, VT', 'Pierre, SD', 'Helena, MT'], c: 1 },
  { q: 'Which two states don\'t observe daylight saving time?', a: ['Hawaii & Arizona', 'Alaska & Hawaii', 'Arizona & Nevada', 'Utah & Hawaii'], c: 0 },
  { q: 'What color are U.S. interstate route shields?', a: ['Green & white', 'Red, white & blue', 'Yellow & black', 'Blue & gold'], c: 1 },
  { q: 'Pikes Peak inspired which famous song?', a: ['This Land Is Your Land', 'America the Beautiful', 'God Bless America', 'Home on the Range'], c: 1 },
  { q: 'How many states border the Pacific Ocean?', a: ['3', '4', '5', '6'], c: 2 },
  { q: 'The "Four Corners" touches Colorado, Utah, Arizona, and…', a: ['Nevada', 'Wyoming', 'New Mexico', 'Texas'], c: 2 },
  { q: 'Which state produces the most corn?', a: ['Nebraska', 'Kansas', 'Illinois', 'Iowa'], c: 3 },
  { q: 'What year did the Interstate Highway System begin?', a: ['1946', '1956', '1966', '1976'], c: 1 },
  { q: 'Which state has a roadrunner as its state bird?', a: ['Arizona', 'Texas', 'New Mexico', 'Nevada'], c: 2 },
  { q: 'The longest main street in America is claimed by Island Park, in which state?', a: ['Idaho', 'Montana', 'Wyoming', 'Utah'], c: 0 },
]

export const SCAVENGER = [
  { label: 'Cow in a field', pts: 5 },
  { label: 'Red barn', pts: 5 },
  { label: 'Water tower with a town name', pts: 10 },
  { label: 'Motorcycle group (3+)', pts: 10 },
  { label: 'RV towing a car', pts: 10 },
  { label: 'Semi truck with a funny slogan', pts: 15 },
  { label: 'Horse trailer', pts: 10 },
  { label: 'Wind turbine', pts: 5 },
  { label: 'Train (moving)', pts: 15 },
  { label: 'Police car', pts: 10 },
  { label: 'Car with a kayak or canoe', pts: 10 },
  { label: 'Out-of-country license plate', pts: 25 },
  { label: 'Rest area sign', pts: 5 },
  { label: 'Historic route marker', pts: 15 },
  { label: 'Hawk or eagle on a fencepost', pts: 20 },
  { label: 'Tunnel', pts: 15 },
  { label: 'Bridge over a big river', pts: 10 },
  { label: 'Billboard for a roadside attraction', pts: 10 },
  { label: 'Someone waving back at you', pts: 20 },
  { label: 'Vintage car (25+ years old)', pts: 15 },
  { label: 'Deer (bonus if it stays put)', pts: 20 },
  { label: 'Giant roadside statue or sculpture', pts: 25 },
  { label: 'Runaway truck ramp', pts: 15 },
  { label: 'State welcome sign', pts: 10 },
]

// ---- Would You Rather: family-friendly this-or-that prompts ----
export const WYR = [
  ['have a pet dinosaur', 'have a pet dragon'],
  ['be able to fly', 'be able to turn invisible'],
  ['only eat pizza forever', 'only eat tacos forever'],
  ['have a car that drives on water', 'have a car that flies'],
  ['be the funniest kid in class', 'be the smartest kid in class'],
  ['have super speed', 'have super strength'],
  ['visit outer space', 'explore the deep ocean'],
  ['have hands for feet', 'have feet for hands'],
  ['be able to talk to animals', 'be able to speak every language'],
  ['live in a treehouse', 'live in a castle'],
  ['always have to sing instead of talk', 'always have to dance while walking'],
  ['have a giant swimming pool', 'have a giant trampoline'],
  ['eat a bug for $100', 'skip dessert for a month'],
  ['be a famous movie star', 'be a famous athlete'],
  ['have it always be summer', 'have it always be winter'],
  ['own a real lightsaber', 'own a real magic wand'],
  ['never have homework again', 'never have chores again'],
  ['have a robot best friend', 'have a talking pet'],
  ['ride a roller coaster all day', 'play video games all day'],
  ['sneeze glitter', 'burp bubbles'],
  ['have a nose that glows when you lie', 'have ears that wiggle when you are happy'],
  ['travel 100 years into the future', 'travel 100 years into the past'],
  ['be able to pause time', 'be able to rewind time'],
  ['have unlimited ice cream', 'have unlimited pizza'],
  ['be as tall as a giraffe', 'be as small as a mouse'],
  ['have a slide instead of stairs', 'have a fire pole instead of stairs'],
  ['control the weather', 'control your dreams'],
  ['have spaghetti for hair', 'have teeth made of marshmallows'],
  ['always win at every game', 'always know the right answer'],
  ['live where it never rains', 'live where it snows every day'],
  ['be a wizard', 'be a superhero'],
  ['have a jetpack', 'have a hoverboard'],
]

// ---- Mad Libs: fill-in-the-blank road stories ----
// %1, %2 … map to the blanks array in order.
export const MADLIBS = [
  {
    title: 'The Big Detour',
    blanks: ['adjective', 'animal (plural)', 'silly food', 'family member', 'verb ending in -ing', 'a number', 'place'],
    text:
      "We were driving down the %1 highway when a herd of %2 blocked the road! " +
      "To get them to move, Dad threw a giant %3 out the window. %4 started %5 so loudly that we had to pull over %6 times before we finally made it to %7.",
  },
  {
    title: 'Are We There Yet?',
    blanks: ['a number', 'adjective', 'body part', 'noun', 'famous person', 'color', 'sound'],
    text:
      "After %1 hours in the car, everyone was getting %2. My %3 was asleep and the back seat smelled like an old %4. " +
      "Suddenly we saw %5 driving a %6 truck, honking and yelling '%7!' It was the weirdest rest stop ever.",
  },
  {
    title: 'The Roadside Diner',
    blanks: ['adjective', 'food', 'liquid', 'animal', 'verb', 'a number', 'exclamation'],
    text:
      "We stopped at a %1 little diner for lunch. I ordered %2 with a tall glass of %3. " +
      "While we ate, a %4 wandered in and tried to %5 my plate! The waiter chased it out %6 times and everyone shouted '%7'",
  },
  {
    title: 'Worlds Greatest Souvenir',
    blanks: ['adjective', 'noun', 'color', 'a number', 'animal', 'verb ending in -ed', 'family member'],
    text:
      "At the gift shop I found the most %1 %2 I had ever seen. It was %3 and cost %4 dollars. " +
      "It had a picture of a %5 on it that %6 whenever you touched it. %7 said it was a waste of money, but I bought two.",
  },
]

// ---- Object Bingo: things to spot, filled onto a 5x5 card ----
export const BINGO_ITEMS = [
  'Red car', 'Blue truck', 'Motorcycle', 'School bus', 'Police car',
  'Cow', 'Horse', 'Dog in a car', 'Bird on a wire', 'Tractor',
  'Water tower', 'Windmill', 'Bridge', 'Tunnel', 'Big flag',
  'Gas station', 'Fast food sign', 'Billboard', 'Rest stop sign', 'Mile marker',
  'License plate from another state', 'RV or camper', 'Boat on a trailer', 'Road work sign', 'Speed limit 70+',
  'Church steeple', 'Barn', 'Bright yellow car', 'Hay bales', 'Airplane in the sky',
  'Lake or pond', 'Mountain', 'Traffic jam', 'Rainbow or cloud shaped like something',
]
