export const STATES = [
  ['AL', 'Alabama'], ['AK', 'Alaska'], ['AZ', 'Arizona'], ['AR', 'Arkansas'],
  ['CA', 'California'], ['CO', 'Colorado'], ['CT', 'Connecticut'], ['DE', 'Delaware'],
  ['DC', 'D.C.'], ['FL', 'Florida'], ['GA', 'Georgia'], ['HI', 'Hawaii'],
  ['ID', 'Idaho'], ['IL', 'Illinois'], ['IN', 'Indiana'], ['IA', 'Iowa'],
  ['KS', 'Kansas'], ['KY', 'Kentucky'], ['LA', 'Louisiana'], ['ME', 'Maine'],
  ['MD', 'Maryland'], ['MA', 'Massachusetts'], ['MI', 'Michigan'], ['MN', 'Minnesota'],
  ['MS', 'Mississippi'], ['MO', 'Missouri'], ['MT', 'Montana'], ['NE', 'Nebraska'],
  ['NV', 'Nevada'], ['NH', 'New Hampshire'], ['NJ', 'New Jersey'], ['NM', 'New Mexico'],
  ['NY', 'New York'], ['NC', 'North Carolina'], ['ND', 'North Dakota'], ['OH', 'Ohio'],
  ['OK', 'Oklahoma'], ['OR', 'Oregon'], ['PA', 'Pennsylvania'], ['RI', 'Rhode Island'],
  ['SC', 'South Carolina'], ['SD', 'South Dakota'], ['TN', 'Tennessee'], ['TX', 'Texas'],
  ['UT', 'Utah'], ['VT', 'Vermont'], ['VA', 'Virginia'], ['WA', 'Washington'],
  ['WV', 'West Virginia'], ['WI', 'Wisconsin'], ['WY', 'Wyoming'],
]

export const TRIVIA = [
  { q: 'Which U.S. interstate is the longest?', a: ['I-90', 'I-80', 'I-10', 'I-95'], c: 0 },
  { q: 'What is the tallest mountain in Colorado?', a: ['Pikes Peak', 'Mount Elbert', 'Longs Peak', 'Mount Evans'], c: 1 },
  { q: 'Route 66 famously ran from Chicago to which city?', a: ['San Francisco', 'Los Angeles', 'Santa Monica', 'San Diego'], c: 2 },
  { q: 'Which state has the most national parks?', a: ['Alaska', 'Utah', 'California', 'Colorado'], c: 2 },
  { q: 'What animal is on the Wyoming license plate?', a: ['Buffalo', 'Bucking horse and rider', 'Eagle', 'Elk'], c: 1 },
  { q: 'The Gateway Arch is in which city?', a: ['Kansas City', 'St. Louis', 'Memphis', 'Nashville'], c: 1 },
  { q: 'Which is the only U.S. state that borders just one other state?', a: ['Maine', 'Florida', 'Alaska', 'Rhode Island'], c: 0 },
  { q: 'What does a yellow diamond road sign usually mean?', a: ['Stop ahead', 'Warning', 'Construction', 'No passing'], c: 1 },
  { q: 'Mount Rushmore is in which state?', a: ['North Dakota', 'Wyoming', 'South Dakota', 'Montana'], c: 2 },
  { q: 'Which Great Lake is entirely within the U.S.?', a: ['Erie', 'Huron', 'Superior', 'Michigan'], c: 3 },
  { q: 'What is the capital of Texas?', a: ['Houston', 'Dallas', 'Austin', 'San Antonio'], c: 2 },
  { q: 'Old Faithful is found in which national park?', a: ['Yosemite', 'Yellowstone', 'Zion', 'Glacier'], c: 1 },
  { q: 'Even-numbered interstates generally run which direction?', a: ['North–south', 'East–west', 'Diagonal', 'In loops'], c: 1 },
  { q: 'Which state is nicknamed the "Centennial State"?', a: ['Utah', 'Nevada', 'Colorado', 'Kansas'], c: 2 },
  { q: 'The Grand Canyon is carved by which river?', a: ['Rio Grande', 'Colorado River', 'Snake River', 'Green River'], c: 1 },
  { q: 'What is the largest state by area?', a: ['Texas', 'California', 'Alaska', 'Montana'], c: 2 },
  { q: 'Which fast-food chain started as a root beer stand in 1919?', a: ['A&W', 'Sonic', 'Dairy Queen', "Wendy's"], c: 0 },
  { q: 'How many U.S. states start with the letter "M"?', a: ['6', '7', '8', '9'], c: 2 },
  { q: 'The world\'s first national park is:', a: ['Yosemite', 'Grand Canyon', 'Yellowstone', 'Great Smoky Mountains'], c: 2 },
  { q: 'Which state\'s license plates say "Live Free or Die"?', a: ['Vermont', 'New Hampshire', 'Maine', 'Montana'], c: 1 },
  { q: 'What is the only U.S. state capital without a McDonald\'s?', a: ['Juneau, AK', 'Montpelier, VT', 'Pierre, SD', 'Helena, MT'], c: 1 },
  { q: 'Which two states don\'t observe daylight saving time?', a: ['Hawaii & Arizona', 'Alaska & Hawaii', 'Arizona & Nevada', 'Utah & Hawaii'], c: 0 },
  { q: 'What color are U.S. interstate route shields?', a: ['Green & white', 'Red, white & blue', 'Yellow & black', 'Blue & gold'], c: 1 },
  { q: 'Pikes Peak inspired which famous song?', a: ['This Land Is Your Land', 'America the Beautiful', 'God Bless America', 'Home on the Range'], c: 1 },
  { q: 'How many states border the Pacific Ocean?', a: ['3', '4', '5', '6'], c: 2 },
  { q: 'The "Four Corners" touches Colorado, Utah, Arizona, and…', a: ['Nevada', 'Wyoming', 'New Mexico', 'Texas'], c: 2 },
  { q: 'Which state produces the most corn?', a: ['Nebraska', 'Kansas', 'Illinois', 'Iowa'], c: 3 },
  { q: 'What year did the Interstate Highway System begin?', a: ['1946', '1956', '1966', '1976'], c: 1 },
  { q: 'Which state has a roadrunner as its state bird?', a: ['Arizona', 'Texas', 'New Mexico', 'Nevada'], c: 2 },
  { q: 'The longest main street in America is claimed by Island Park, in which state?', a: ['Idaho', 'Montana', 'Wyoming', 'Utah'], c: 0 },
]

export const SCAVENGER = [
  { label: 'Cow in a field', pts: 5 },
  { label: 'Red barn', pts: 5 },
  { label: 'Water tower with a town name', pts: 10 },
  { label: 'Motorcycle group (3+)', pts: 10 },
  { label: 'RV towing a car', pts: 10 },
  { label: 'Semi truck with a funny slogan', pts: 15 },
  { label: 'Horse trailer', pts: 10 },
  { label: 'Wind turbine', pts: 5 },
  { label: 'Train (moving)', pts: 15 },
  { label: 'Police car', pts: 10 },
  { label: 'Car with a kayak or canoe', pts: 10 },
  { label: 'Out-of-country license plate', pts: 25 },
  { label: 'Rest area sign', pts: 5 },
  { label: 'Historic route marker', pts: 15 },
  { label: 'Hawk or eagle on a fencepost', pts: 20 },
  { label: 'Tunnel', pts: 15 },
  { label: 'Bridge over a big river', pts: 10 },
  { label: 'Billboard for a roadside attraction', pts: 10 },
  { label: 'Someone waving back at you', pts: 20 },
  { label: 'Vintage car (25+ years old)', pts: 15 },
  { label: 'Deer (bonus if it stays put)', pts: 20 },
  { label: 'Giant roadside statue or sculpture', pts: 25 },
  { label: 'Runaway truck ramp', pts: 15 },
  { label: 'State welcome sign', pts: 10 },
]
